### ISSUE TITLE
RangeError:  Maximum call stack size exceeded

### ISSUE THREAD

**Issue by bsdt-snelson** [michaelkourlas/node-js2xmlparser#56]
Got Maximum call stack size exceeded error when parsing JSON file containing pdf binaries around 3MB.  Is there a configuration setting in the library to increase the call stack size?

**Comment by michaelkourlas** [comment]
Could you upload or email me a sample file that causes this problem? Also, what JS engine are you using? Node or something else?

Call stack size definitely wouldn't be configurable on the library side; you'd have to start the runtime with a larger size.

**Comment by arulselvan** [comment]
Getting same issue, attached data in JSON format for testing, I think its happening only on nested level
cod snip:
    //xml conversion
   // lowerThird is js object from attached txt
   let xmlDoc = js2xmlparser.parse("LowerThird", lowerThird);

error message : "Maximum call stack size exceeded"
stack:
ex.stack
"RangeError: Maximum call stack size exceeded
    at RegExp.exec (native)
    at RegExp.test (native)
    at Object.validateName (c:\Projects\ams-lta-mean\node_modules\xmlcreate\lib\validate.js:92:14)
    at XmlElement.set [as name] (c:\Projects\ams-lta-mean\node_modules\xmlcreate\lib\nodes\XmlElement.js:93:34)
    at new XmlElement (c:\Projects\ams-lta-mean\node_modules\xmlcreate\lib\nodes\XmlElement.js:72:20)
    at XmlElement.element (c:\Projects\ams-lta-mean\node_modules\xmlcreate\lib\nodes\XmlElement.js:218:23)
    at c:\Projects\ams-lta-mean\node_modules\js2xmlparser\lib\main.js:190:36
    at Array.forEach (native)
    at parseArrayOrSet (c:\Projects\ams-lta-mean\node_modules\js2xmlparser\lib\main.js:187:16)
    at parseValue (c:\Projects\ams-lta-mean\node_modules\js2xmlparser\lib\main.js:224:9)
    at parseObjectOrMapEntry (c:\Projects\ams-lta-mean\node_modules\js2xmlparser\lib\main.js:132:5)
    at parseObjectOrMap (c:\Projects\ams-lta-mean\node_modules\js2xmlparser\lib\main.js:152:13)
    at parseValue (c:\Projects\ams-lta-mean\node_modules\js2xmlparser\lib\main.js:220:9)
    at c:\Projects\ams-lta-mean\node_modules\js2xmlparser\lib\main.js:192:9
    at Array.forEach (native)
    at parseArrayOrSet (c:\Projects\ams-lta-mean\node_modules\js2xmlparser\lib\main.js:187:16)"

[js2xmlissue.txt](https://github.com/michaelkourlas/node-js2xmlparser/files/1277050/js2xmlissue.txt)

**Comment by kaleguy** [comment]
The function validateChar in xmlCreate breaks when passed a large string since it is using a regular expression to check the string. (Regular expressions use recursion). 

You can avoid the issue by doing something like this (instead of a regex):

```
function validateLongStr(str) {
  const re = new RegExp("^\\u0009|\\u000A|\\u000D|[\\u0020-\\uD7FF]|[\\uE000-\\uFFFD]$")
  for (let i = 0; i < str.length; i++) {
    if (!re.test(str[i])) {
      return false
    }
  }
  return true
}
```

**Comment by michaelkourlas** [comment]
Thanks for the analysis -- I'll fix this soon.

**Comment by michaelkourlas** [comment]
This is now fixed in the next version of xmlcreate, which will be used in the next version of js2xmlparser.

**Comment by UltraCakeBakery** [comment]
Is this problem really solved?

code: `js2xmlparser.parse( 'trafficState', { data } )`

JSON: https://pastebin.com/m9PMz9L4

error in console:
> RangeError: Maximum call stack size exceeded
    at C:\bitbucket\projectname\node_modules\js2xmlparser\lib\main.js:208:33
    at CoreDocumentArray.forEach (<anonymous>)
    at parseArrayOrSet (C:\bitbucket\projectname\node_modules\js2xmlparser\lib\main.js:208:16)      
    at parseValue (C:\bitbucket\projectname\node_modules\js2xmlparser\lib\main.js:245:9)
    at parseObjectOrMapEntry (C:\bitbucket\projectname\node_modules\js2xmlparser\lib\main.js:162:5) 
    at parseObjectOrMap (C:\bitbucket\projectname\node_modules\js2xmlparser\lib\main.js:178:13)     
    at parseValue (C:\bitbucket\projectname\node_modules\js2xmlparser\lib\main.js:241:9)
    at C:\bitbucket\projectname\node_modules\js2xmlparser\lib\main.js:224:9
    at CoreDocumentArray.forEach (<anonymous>)
    at parseArrayOrSet (C:\bitbucket\projectname\node_modules\js2xmlparser\lib\main.js:208:16)      
    at parseValue (C:\bitbucket\projectname\node_modules\js2xmlparser\lib\main.js:245:9)
    at parseObjectOrMapEntry (C:\bitbucket\projectname\node_modules\js2xmlparser\lib\main.js:162:5) 
    at parseObjectOrMap (C:\bitbucket\projectname\node_modules\js2xmlparser\lib\main.js:178:13)     
    at parseValue (C:\bitbucket\projectname\node_modules\js2xmlparser\lib\main.js:241:9)
    at C:\bitbucket\projectname\node_modules\js2xmlparser\lib\main.js:224:9
    at CoreDocumentArray.forEach (<anonymous>)
